### ISSUE TITLE
'StoreWriteSettings.type can not be None' exception when creating a pipeline with linked service of type Azure File Storage

### ISSUE THREAD

**Issue by antgonmir** [Azure/azure-sdk-for-python#12735]
- **Package Name**: azure-mgmt-datafactory
- **Package Version**: 0.11.0
- **Operating System**: Linux
- **Python Version**: 3x

**Describe the bug**
**pipelines.create_or_update** in **DataFactoryManagementClient** results in the following exception if the pipeline uses a linked service of type **Azure File Storage**:

```
2020-07-20 02:25:14,574 - msrest.serialization - WARNING:
 Subtype value AzureFileStorageWriteSettings has no mapping, use base class StoreWriteSettings.
Traceback (most recent call last):
  File "deployment_service/src/deployment_main/deployment.py", line 158, in <module>
    adfjson_main()
  File "/apps/agent/_work/15/s/venv/lib64/python3.6/site-packages/deployment_adfjson/deployment_adfjson.py", line 50, in adfjson_main
    generate_adf_pipeline_adfjson(df_client, pipeline_spec_pl_path)
  File "/apps/agent/_work/15/s/venv/lib64/python3.6/site-packages/deployment_adfjson/deployment_adfjson_utils.py", line 52, in generate_adf_pipeline_adfjson
    df_client.pipelines.create_or_update(rg_name, adf_name, pipeline["name"], pipeline)
  File "/apps/agent/_work/15/s/venv/lib64/python3.6/site-packages/azure/mgmt/datafactory/operations/_pipelines_operations.py", line 168, in create_or_update
    body_content = self._serialize.body(pipeline, 'PipelineResource')
  File "/apps/agent/_work/15/s/venv/lib64/python3.6/site-packages/msrest/serialization.py", line 625, in body
    raise errors[0]
  File "/apps/agent/_work/15/s/venv/lib64/python3.6/site-packages/msrest/serialization.py", line 250, in validate
    Serializer.validate(value, debug_name, **self._validation.get(attr_name, {}))
  File "/apps/agent/_work/15/s/venv/lib64/python3.6/site-packages/msrest/serialization.py", line 727, in validate
    raise ValidationError("required", name, True)
msrest.exceptions.ValidationError: Parameter 'StoreWriteSettings.type' can not be None.
```
The **pipeline** object is read directly from the pipeline specifications committed by Data Factory into a linked repository (or can be taken from the code pane in Data Factory). The issue does not occur if a linked service of type **File System** is used instead.  

**To Reproduce**
1. Instantiate a DataFactoryManagementClient instance with the desired authentication mechanism, in this example 'df_client'
2. Read the JSON representation of an Azure Data Factory pipeline that contains a Dataset using a linked service of type **Azure File Storage** into an object, in this case 'pipeline'
3. Provided the linked services and datasets exist in the Data Factory instance, call the **pipelines.create_or_update** method with the appropriate parameters:
`df_client.pipelines.create_or_update(rg_name, adf_name, pipeline["name"], pipeline)`

**Expected behavior**
The pipeline should be created in Data Factory. 

**Additional context**
The issue does not occur if a linked service of type **File System** is used instead.

**Comment by qiaozha** [comment]
@antgonmir Can you share more details about the pipeline definition? What kind of activities are you trying to create? What's your dataset definition?

**Comment by qiaozha** [comment]
After furthur investigation, there is because there's no definition of AzureFileStorageWriteSettings in the swagger https://github.com/Azure/azure-rest-api-specs/blob/master/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json, but it has AzureFileStorageReadSettings. Add service attention here.

**Comment by shawnxzq** [comment]
This will be fixed with next PS release, which is scheduled to 9/22 this month, close the issue for now.

**Comment by shawnxzq** [comment]
@qiaozha I can close this issue, could you please help give me the permission to close the issue? thanks!

**Comment by qiaozha** [comment]
The normal process of closing a issue should be the issue author. 
I think we can keep it here, once the new SDK released we can give a update here and add a needs-author-feedback label which will close the issue within 7 days automatically if no response from the issue author since add this label.

**Comment by shawnxzq** [comment]
@qiaozha This is already fixed, please notify the author to verify and close this one, thanks!

**Comment by qiaozha** [comment]
@shawnxzq I still can't find the definition of https://raw.githubusercontent.com/Azure/azure-sdk-for-python/master/sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py here? Have you submitted a release request and has the SDK been released yet?

**Comment by shawnxzq** [comment]
@qiaozha We released Phython SDK several days ago, could you please double confirm the issue? Thanks!

**Comment by qiaozha** [comment]
@shawnxzq now I can see the definition now.
@antgonmir  You may use https://pypi.org/project/azure-mgmt-datafactory/0.14.0/ to resolve this issue. Thanks
