### ISSUE TITLE
scheduler - jobs.get function fails if custom retry policy is set

### ISSUE THREAD

**Issue by smereczynski** [Azure/azure-sdk-for-python#1358]
If we will configure scheduler job with retry policy other than default or none (so we will configure it as custom):

![2017-08-11_17-24-25](https://user-images.githubusercontent.com/705653/29219983-f3ecaa58-7eb9-11e7-8810-caa9690e9cff.png)

and then we will try to use SchedulerManagementClient to get this job, using jobs.get() function, we will get "isodate.isoerror.ISO8601Error: Unable to parse duration string '00:00:15'":

```/Users/michal/dev/azure_python/venv/bin/python /Users/michal/dev/azure_python/scheduler.py
Traceback (most recent call last):
  File "/Users/michal/dev/azure_python/venv/lib/python3.6/site-packages/msrest/serialization.py", line 1070, in deserialize_duration
    duration = isodate.parse_duration(attr)
  File "/Users/michal/dev/azure_python/venv/lib/python3.6/site-packages/isodate/isoduration.py", line 102, in parse_duration
    raise ISO8601Error("Unable to parse duration string %r" % datestring)
isodate.isoerror.ISO8601Error: Unable to parse duration string '00:00:15'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/michal/dev/azure_python/scheduler.py", line 40, in <module>
    job_name='job1')
  File "/Users/michal/dev/azure_python/venv/lib/python3.6/site-packages/azure/mgmt/scheduler/operations/jobs_operations.py", line 95, in get
    deserialized = self._deserialize('JobDefinition', response)
  File "/Users/michal/dev/azure_python/venv/lib/python3.6/site-packages/msrest/serialization.py", line 761, in __call__
    value = self.deserialize_data(raw_value, attr_type)
  File "/Users/michal/dev/azure_python/venv/lib/python3.6/site-packages/msrest/serialization.py", line 879, in deserialize_data
    return self(obj_type, data)
  File "/Users/michal/dev/azure_python/venv/lib/python3.6/site-packages/msrest/serialization.py", line 761, in __call__
    value = self.deserialize_data(raw_value, attr_type)
  File "/Users/michal/dev/azure_python/venv/lib/python3.6/site-packages/msrest/serialization.py", line 879, in deserialize_data
    return self(obj_type, data)
  File "/Users/michal/dev/azure_python/venv/lib/python3.6/site-packages/msrest/serialization.py", line 761, in __call__
    value = self.deserialize_data(raw_value, attr_type)
  File "/Users/michal/dev/azure_python/venv/lib/python3.6/site-packages/msrest/serialization.py", line 879, in deserialize_data
    return self(obj_type, data)
  File "/Users/michal/dev/azure_python/venv/lib/python3.6/site-packages/msrest/serialization.py", line 761, in __call__
    value = self.deserialize_data(raw_value, attr_type)
  File "/Users/michal/dev/azure_python/venv/lib/python3.6/site-packages/msrest/serialization.py", line 863, in deserialize_data
    data_val = self.deserialize_type[data_type](data)
  File "/Users/michal/dev/azure_python/venv/lib/python3.6/site-packages/msrest/serialization.py", line 1073, in deserialize_duration
    raise_with_traceback(DeserializationError, msg, err)
  File "/Users/michal/dev/azure_python/venv/lib/python3.6/site-packages/msrest/exceptions.py", line 47, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/Users/michal/dev/azure_python/venv/lib/python3.6/site-packages/msrest/serialization.py", line 1070, in deserialize_duration
    duration = isodate.parse_duration(attr)
  File "/Users/michal/dev/azure_python/venv/lib/python3.6/site-packages/isodate/isoduration.py", line 102, in parse_duration
    raise ISO8601Error("Unable to parse duration string %r" % datestring)
msrest.exceptions.DeserializationError: Cannot deserialize duration object., ISO8601Error: Unable to parse duration string '00:00:15'

Process finished with exit code 1
```

if we will configure none retry policy, everything is ok:

![2017-08-11_17-29-05](https://user-images.githubusercontent.com/705653/29220183-98a36c58-7eba-11e7-916e-0498052a9e5f.png)

```
/Users/michal/dev/azure_python/venv/bin/python /Users/michal/dev/azure_python/scheduler.py

Process finished with exit code 0
```

If we will configure it with default value (4 times / 30 sec):
![2017-08-11_17-30-24](https://user-images.githubusercontent.com/705653/29220259-cb98c41e-7eba-11e7-9dba-e1f285a91fc2.png)

everything seems to be ok, but... if we will get retry policy definition from the API with `print(async_scheduler_job.properties.action.retry_policy)` then:

```
{'retry_type': <RetryType.fixed: 'Fixed'>, 'retry_interval': None, 'retry_count': None}
```

But should be 4/30 as described in the portal.

Looking at the error: `isodate.isoerror.ISO8601Error: Unable to parse duration string '00:00:15'` it seems that API is returning '00:00:15' not ISO8601 formatted period with P at the beginning.

**Comment by lmazuel** [comment]
Hi @smereczynski 
This is a server side issue, the service is not supposed to return `00:00:15`, but `PT15S`. I will reach out the service team about this.
If you need a quick workaround by editing the Python code tell me, since I need to wait for a fix at the RestAPI level it might take a certain amount of time.

**Comment by lmazuel** [comment]
@smereczynski 
Update: I released msrest 0.4.14 that gives me the necessary tools to fix it. Still in progress.

**Comment by smereczynski** [comment]
@lmazuel it is still failing with msrest 0.4.14. I appreciate that it is in progress. Waiting for update :)

**Comment by smereczynski** [comment]
P.S. @lmazuel in msrest v. 0.4.12, 0.4.13 and 0.4.14 there is a serialization errror during some operations (in my case, during attaching managed disk to the VM): https://gist.github.com/smereczynski/0eead16c2101100faab99648d1a3bf28

I think it should be rolled back to 0.4.11 - where it works. I see regression in changelog: https://pypi.python.org/pypi/msrest

My code:

    vm2.storage_profile.data_disks.append({
                'lun': 0,
                'name': managed_disk.name,
                'create_option': DiskCreateOption.attach,
                'managed_disk': {
                    'id': managed_disk.id
                }
            })

**Comment by lmazuel** [comment]
PS @smereczynski The new code is correct, 'create_option' is supposed to be typed `DiskCreateOptionsType`. See here https://docs.microsoft.com/en-us/python/api/azure.mgmt.compute.compute.v2017_03_30.models.datadisk?view=azure-python
This was not checked before.

**Comment by lmazuel** [comment]
Hi @smereczynski 
I released the fix:
https://pypi.python.org/pypi/azure-mgmt-scheduler/1.1.3

I'm closing this one, but feel free to still comment on it if I missed something, or open a new issue if you find another issue.
Thanks!
