### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'iter'

### ISSUE THREAD

**Issue by stevenylai** [Azure/azure-sdk-for-python#15956]
- **Package Name**: azure-storage-file-datalake
- **Package Version**: 12.2.0
- **Operating System**: Linux
- **Python Version**: 3.5.2 (from HDInsight cluster with ESP)

**Describe the bug**
When listing an Azure directory which doesn't have proper permission, we get AttributeError. Traceback:
```
Traceback (most recent call last):
  File "azure.whl/azure/storage/filedatalake/_list_paths_helper.py", line 56, in _get_next_cb
  File "azure.whl/azure/storage/filedatalake/_generated/operations/_file_system_operations.py", line 442, in list_paths
azure.storage.filedatalake._generated.models._models_py3.StorageErrorException: (AuthorizationPermissionMismatch) This request is not authorized to perform this operation using this permission.
RequestId:e6038639-e01f-007e-5013-df0d71000000
Time:2020-12-31T01:21:21.9445915Z

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_client.py", line 18, in <module>
    for run_result in fs_client.get_paths(path='rtgasi/negotiation/hdfs_rfe_v1/results/205ba9c9-8cdb-4f77-887f-c561e2c8edc3', recursive=False):
  File "azure.whl/azure/core/paging.py", line 129, in __next__
  File "azure.whl/azure/core/paging.py", line 76, in __next__
  File "azure.whl/azure/storage/filedatalake/_list_paths_helper.py", line 58, in _get_next_cb
  File "azure.whl/azure/storage/filedatalake/_shared/response_handlers.py", line 94, in process_storage_error
AttributeError: 'dict' object has no attribute 'iter'
```

**To Reproduce**
1. Just run the following code where `some/path` does not have the proper permission:
```python
credential = identity.ClientSecretCredential('xx', 'xx', 'xx')
service_client = filedatalake.DataLakeServiceClient('https://xx.dfs.core.windows.net', credential=credential)
fs_client = service_client.get_file_system_client(file_system='xx')
for result in fs_client.get_paths(path='some/path', recursive=False):
  pass
```

**Expected behavior**
Should raise `StorageErrorException` or other more relevant errors

From the look of the exception, we just need to remove `.iter()` part and it should work for both Python 2 and 3:
https://github.com/Azure/azure-sdk-for-python/blob/d59d06d75131f4e5ac133bcfdc442c38416808ad/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/response_handlers.py#L94

**Screenshots**

**Additional context**

**Comment by xiafu-msft** [comment]
Hi @stevenylai 

Thanks for reaching out! it looks like we have a similar issue here https://github.com/Azure/azure-sdk-for-python/issues/15871 
We will try to fix this ASAP!

**Comment by jbschiratti** [comment]
@xiafu-msft I think that have the same problem!

Here is my code:
```
from azure.storage.blob import BlobServiceClient, ContainerClient
from azure.identity import ClientSecretCredential

token_credential =  ClientSecretCredential(tenant_id='WWW',
                                           client_id='XXX',
                                           client_secret='YYY')

service = BlobServiceClient("ZZZ", credential=token_credential)

container_client = service.get_container_client(container='AAA')

print(container_client.container_name)

blob_list = container_client.list_blobs()

for blob in blob_list:
    print(blob.name + '\n')
```

The last line throws this error:

```
---------------------------------------------------------------------------
StorageErrorException                     Traceback (most recent call last)
/anaconda/envs/azureml_py36_automl/lib/python3.6/site-packages/azure/storage/blob/_list_blobs_helper.py in _get_next_cb(self, continuation_token)
     75                 cls=return_context_and_deserialized,
---> 76                 use_location=self.location_mode)
     77         except StorageErrorException as error:

/anaconda/envs/azureml_py36_automl/lib/python3.6/site-packages/azure/storage/blob/_generated/operations/_container_operations.py in list_blob_flat_segment(self, prefix, marker, maxresults, include, timeout, request_id, cls, **kwargs)
   1215             map_error(status_code=response.status_code, response=response, error_map=error_map)
-> 1216             raise models.StorageErrorException(response, self._deserialize)
   1217 

StorageErrorException: (InvalidQueryParameterValue) Value for one of the query parameters specified in the request URI is invalid.
RequestId:39f9e5c3-201f-0114-551d-efab6d000000
Time:2021-01-20T11:13:03.6566856Z

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-6-a064d97987b5> in <module>
----> 1 for blob in blob_list:
      2     print(blob.name + '\n')

/anaconda/envs/azureml_py36_automl/lib/python3.6/site-packages/azure/core/paging.py in __next__(self)
    127         if self._page_iterator is None:
    128             self._page_iterator = itertools.chain.from_iterable(self.by_page())
--> 129         return next(self._page_iterator)
    130 
    131     next = __next__  # Python 2 compatibility.

/anaconda/envs/azureml_py36_automl/lib/python3.6/site-packages/azure/core/paging.py in __next__(self)
     74             raise StopIteration("End of paging")
     75         try:
---> 76             self._response = self._get_next(self.continuation_token)
     77         except AzureError as error:
     78             if not error.continuation_token:

/anaconda/envs/azureml_py36_automl/lib/python3.6/site-packages/azure/storage/blob/_list_blobs_helper.py in _get_next_cb(self, continuation_token)
     76                 use_location=self.location_mode)
     77         except StorageErrorException as error:
---> 78             process_storage_error(error)
     79 
     80     def _extract_data_cb(self, get_next_return):

/anaconda/envs/azureml_py36_automl/lib/python3.6/site-packages/azure/storage/blob/_shared/response_handlers.py in process_storage_error(storage_error)
     92         error_body = ContentDecodePolicy.deserialize_from_http_generics(storage_error.response)
     93         if error_body:
---> 94             for info in error_body.iter():
     95                 if info.tag.lower() == 'code':
     96                     error_code = info.text

AttributeError: 'dict' object has no attribute 'iter'
```

Am I doing something wrong? Or is it a bug with `azure-storage-blob`?

**Comment by tasherif-msft** [comment]
Hi @jbschiratti and @stevenylai! This issue should have been resolved in our most recent release :)
If you could update your datalake version to 12.2.2 and let me know if this issue still persists there.

Thank you.

**Comment by tasherif-msft** [comment]
Hi @jbschiratti, I will investigate blob for this issue as well and let you know!

**Comment by tasherif-msft** [comment]
Hi @jbschiratti, this issue should also be resolved in our most recent blob package (12.7.1) please confirm that this issue no longer persists.

**Comment by prevostc** [comment]
@tasherif-msft the 12.7.1 does not fix the issue: https://github.com/Azure/azure-sdk-for-python/blob/e8edeb85bcb9f92cb3c6299b893eb99be55bdd51/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/response_handlers.py#L97

This line contains `.iter()` which as of my small understanding of python is not python 3 compatible.
The result is that I cannot see the returned error :s

**Comment by tasherif-msft** [comment]
Hi @prevostc, it's my bad I was under the impression that we had resolved this bug. I will put a PR to fix it asap. 
Sorry for the inconvenience this has caused.

**Comment by tasherif-msft** [comment]
Hi @prevostc, it is supported in Py3, you can call `.iter()` on `elementtree` objects which in this case it is.
Could you please provide me a code sample of what you're attempting to do and how that's failing?

**Comment by prevostc** [comment]
My bad, I used a BlobClient with a Datalake container. 
In this case, the object returned was a dict and .iter() errored without showing me the actual content of the response.
It's fixed for me now, but you may want to check this case to help dump people like me :D
