### ISSUE TITLE
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode()

### ISSUE THREAD

**Issue by gison93** [Azure/azure-sdk-for-python#16035]
- **Package Name**: azureml-core
- **Package Version**: 1.18.0.post1
- **Operating System**: vs2017-win2016
- **Python Version**: 3.6.8

**Describe the bug**
Launching the build of a ML pipeline I get the following error before it's able to start the first step:
```
It is required that you pass in a value for the "algorithms" argument when calling decode().'
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode()
```

**To Reproduce**
1. 

**Expected behavior**
That the pipeline starts without problem.

**Additional context**
PyJWT is pinned to version 1.7.1
On a different Azure Machine Learning the pipelines run without issues.

**Comment by ponkumarpandian** [comment]
I am also getting the same error and it was working fine in another subscription. Any update on this issue?

**Comment by ponkumarpandian** [comment]
Here is the workaround need downgrade the azureml.core lib to 1.18.0 and it worked for me.

**Comment by vkb1** [comment]
Thanks @ponkumarpandian, the 1.18.0 version of azureml-core lib worked for me. 

We were using the 1.4.0 version of azureml-core lib so far and things w.r.t Azure ML workspace were working as expected but recently we started seeing the `jwt.exceptions.DecodeError`. Below is the call stack:

```
File "/usr/local/lib/python3.6/dist-packages/azureml/core/workspace.py", line 483, in get
    result_dict = Workspace.list(subscription_id, auth=auth, resource_group=resource_group)
  File "/usr/local/lib/python3.6/dist-packages/azureml/core/workspace.py", line 546, in list
    workspaces_list = Workspace._list_legacy(auth, subscription_id=subscription_id)
  File "/usr/local/lib/python3.6/dist-packages/azureml/core/workspace.py", line 1107, in _list_legacy
    raise e
  File "/usr/local/lib/python3.6/dist-packages/azureml/core/workspace.py", line 1101, in _list_legacy
    resource_group_name=resource_group_name)
  File "/usr/local/lib/python3.6/dist-packages/azureml/_project/_commands.py", line 395, in list_workspace
    return ml_workspace_list(auth, subscription_id, resource_group_name=resource_group_name)
  File "/usr/local/lib/python3.6/dist-packages/azureml/_workspace/custom.py", line 163, in ml_workspace_list
    rcf = resource_client_factory(auth, subscription_id)
  File "/usr/local/lib/python3.6/dist-packages/azureml/_base_sdk_common/common.py", line 348, in resource_client_factory
    return auth._get_service_client(ResourceManagementClient, subscription_id)
  File "/usr/local/lib/python3.6/dist-packages/azureml/core/authentication.py", line 144, in _get_service_client
    all_subscription_list, tenant_id = self._get_all_subscription_ids()
  File "/usr/local/lib/python3.6/dist-packages/azureml/core/authentication.py", line 1020, in _get_all_subscription_ids
    return arm_auth._get_all_subscription_ids()
  File "/usr/local/lib/python3.6/dist-packages/azureml/core/authentication.py", line 799, in _get_all_subscription_ids
    token_tenant_id = fetch_tenantid_from_aad_token(arm_token)
  File "/usr/local/lib/python3.6/dist-packages/azureml/_base_sdk_common/common.py", line 116, in fetch_tenantid_from_aad_token
    decode_json = jwt.decode(token, verify=False)
  File "/usr/local/lib/python3.6/dist-packages/jwt/api_jwt.py", line 113, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jwt/api_jwt.py", line 80, in decode_complete
    'It is required that you pass in a value for the "algorithms" argument when calling decode().'
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().
```

Are we seeing this issue due to an update in Azure cloud which is causing this breakage? Is there a way we can make sure pro-actively that an update in Azure cloud doesn't cause breakages like this or inform users to update to the working version of azureml-core library becz the latest version of 1.20.0 gives a diff problem as below:

```
  File "/usr/local/lib/python3.6/dist-packages/azureml/core/workspace.py", line 581, in get
    workspace_name=name)
  File "/usr/local/lib/python3.6/dist-packages/azureml/_project/_commands.py", line 381, in get_workspace
    workspace_name)
  File "/usr/local/lib/python3.6/dist-packages/azureml/_base_sdk_common/workspace/operations/workspaces_operations.py", line 66, in get
    'resourceGroupName': self._serialize.url("resource_group_name", resource_group_name, 'str'),
  File "/usr/local/lib/python3.6/dist-packages/msrest/serialization.py", line 648, in url
    data = self._http_component_validation(data, data_type, name, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/msrest/serialization.py", line 636, in _http_component_validation
    data = self.validate(data, name, required=True, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/msrest/serialization.py", line 730, in validate
    raise ValidationError("required", name, True)
msrest.exceptions.ValidationError: Parameter 'resource_group_name' can not be None.
```

Let me know if you have any questions.

**Comment by gison93** [comment]
Thank you @ponkumarpandian for the hint!
I upgraded the package to version 1.20.0 and now everything works.

**Comment by gison93** [comment]
Hi @nickzhums, are there some updates in the azure sdk that could have caused these issues?

**Comment by nickzhums** [comment]
this seems to be a package that's outside our team's domain knowledge. @00Kai0 @jsntcy do you guys have knowledge about this?

**Comment by 00Kai0** [comment]
Hi @gison93 , could you show your package list with `pip list`. It seem like that you are using a higher version of `pyJWT`.

Recurrence Error:
```bash
# With pyJWT==1.7.1
>>> import jwt
>>> token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik5FRTFRVVJCT1RNNE16STVSa0ZETlRZeE9UVTFNRGcyT0Rnd1EwVXpNVGsxUWpZeVJrUkZRdyJ9.eyJpc3MiOiJodHRwczovL2Rldi04N2V2eDlydS5hdXRoMC5jb20vIiwic3ViIjoiYVc0Q2NhNzl4UmVMV1V6MGFFMkg2a0QwTzNjWEJWdENAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vZXhwZW5zZXMtYXBpIiwiaWF0IjoxNTcyMDA2OTU0LCJleHAiOjE1NzIwMDY5NjQsImF6cCI6ImFXNENjYTc5eFJlTFdVejBhRTJINmtEME8zY1hCVnRDIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.PUxE7xn52aTCohGiWoSdMBZGiYAHwE5FYie0Y1qUT68IHSTXwXVd6hn02HTah6epvHHVKA2FqcFZ4GGv5VTHEvYpeggiiZMgbxFrmTEY0csL6VNkX1eaJGcuehwQCRBKRLL3zKmA5IKGy5GeUnIbpPHLHDxr-GXvgFzsdsyWlVQvPX2xjeaQ217r2PtxDeqjlf66UYl6oY6AqNS8DH3iryCvIfCcybRZkc_hdy-6ZMoKT6Piijvk_aXdm7-QQqKJFHLuEqrVSOuBqqiNfVrG27QzAPuPOxvfXTVLXL2jek5meH6n-VWgrBdoMFH93QEszEDowDAEhQPHVs0xj7SIzA"
>>> jwt.decode(token, verify=False)
{'iss': 'https://dev-87evx9ru.auth0.com/', 'sub': 'aW4Cca79xReLWUz0aE2H6kD0O3cXBVtC@clients', 'aud': 'https://expenses-api', 'iat': 1572006954, 'exp': 1572006964, 'azp': 'aW4Cca79xReLWUz0aE2H6kD0O3cXBVtC', 'gty': 'client-credentials'}
```

```bash
# with pyJWT==2.0.0
>>> import jwt
>>> token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik5FRTFRVVJCT1RNNE16STVSa0ZETlRZeE9UVTFNRGcyT0Rnd1EwVXpNVGsxUWpZeVJrUkZRdyJ9.eyJpc3MiOiJodHRwczovL2Rldi04N2V2eDlydS5hdXRoMC5jb20vIiwic3ViIjoiYVc0Q2NhNzl4UmVMV1V6MGFFMkg2a0QwTzNjWEJWdENAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vZXhwZW5zZXMtYXBpIiwiaWF0IjoxNTcyMDA2OTU0LCJleHAiOjE1NzIwMDY5NjQsImF6cCI6ImFXNENjYTc5eFJlTFdVejBhRTJINmtEME8zY1hCVnRDIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.PUxE7xn52aTCohGiWoSdMBZGiYAHwE5FYie0Y1qUT68IHSTXwXVd6hn02HTah6epvHHVKA2FqcFZ4GGv5VTHEvYpeggiiZMgbxFrmTEY0csL6VNkX1eaJGcuehwQCRBKRLL3zKmA5IKGy5GeUnIbpPHLHDxr-GXvgFzsdsyWlVQvPX2xjeaQ217r2PtxDeqjlf66UYl6oY6AqNS8DH3iryCvIfCcybRZkc_hdy-6ZMoKT6Piijvk_aXdm7-QQqKJFHLuEqrVSOuBqqiNfVrG27QzAPuPOxvfXTVLXL2jek5meH6n-VWgrBdoMFH93QEszEDowDAEhQPHVs0xj7SIzA"
>>> jwt.decode(token, verify=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\test\test_azureml\venv\lib\site-packages\jwt\api_jwt.py", line 113, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "D:\test\test_azureml\venv\lib\site-packages\jwt\api_jwt.py", line 79, in decode_complete
    raise DecodeError(
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().
```

cc @nickzhums @jsntcy

**Comment by jsntcy** [comment]
@bandsina, any insights on this issue?

**Comment by gison93** [comment]
Hi @00Kai0, I confirm you that I had PyJWT==1.7.1. with azureml-core==1.18.0.post1.
Using azureml-core==1.20.0, keeping PyJWT==1.7.1, solves the issue.

**Comment by needuv** [comment]
Hi @gison93, sorry you were facing this issue. Are you still blocked? Or, has your issue been resolved with upgrading azureml-core to 1.20.0?  Here is our TSG for troubleshooting this and other issues: https://msdata.visualstudio.com/Vienna/_git/vienna/pullrequest/519703

**Comment by gison93** [comment]
Hi @needuv,  updating azureml-core  to version 1.20.0 solves the issue. Clicking on the TSG link returns 401 error.

**Comment by needuv** [comment]
@gison93 sorry about that. Just updated the link with the proper TSG.

**Comment by bandsina** [comment]
#please-close because this issue is now resolved.

**Comment by swatig007** [comment]
closing since this issue is resolved

**Comment by markokole** [comment]
When facing this error, I kept my azure-core at 1.9.0 and downgraded PyJWT to 1.7.1 (from 2.0.1) and it worked.

**Comment by Thalinda** [comment]
i got the same issues so if some one still get hte same issues try this
```
token = jwt.encode({'user_id':user_id,'exp':datetime.datetime.utcnow()+datetime.timedelta(minutes=1440)},SECRET, algorithm="HS256")
    data = jwt.decode(token,SECRET,algorithms="HS256")
```
you have to passe the alogrithms

**Comment by OleksiyKH0240** [comment]
@Thalinda, thank you man

**Comment by ankan-withadream** [comment]
Here's a NOTE: ( I made this silly mistake :( Hope this helps someone )
 you have to pass a value as ' algorithm ' in jwt.encode( ) and not ' algorithms '
 but you have to pass value as ' algorithms ' in jwt.decode( ) and not ' algorithm '

**Comment by SHLGL282** [comment]
Hi, I am facing same kind of issue. May I get to know how I can downgrade package to a particular version.
PyJWT ==2.1.0 and want to move to 1.7.1 version.

**Comment by Niki2199** [comment]
Hi, i am working in virtual environment , and i have PyJWT==1.7.1, Its still giving this error
`jwt.exceptions.DecodeError:` It is required that you pass in a value for the "algorithms" argument when calling decode().`

But when i deactivate the env, it's working perfectly fine with 1.7.1! Can someone help? I want it to work on venv
