### ISSUE TITLE
ImportError: No module named common.credentials

### ISSUE THREAD

**Issue by vnimbalkar** [Azure/azure-sdk-for-python#1607]
Facing below issue on running my pyhton file:

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    from azure.common.credentials import ServicePrincipalCredentials
ImportError: No module named common.credentials

pip show azure
Name: azure
Version: 2.0.0rc5
Summary: Microsoft Azure Client Libraries for Python
Home-page: https://github.com/Azure/azure-sdk-for-python
Author: Microsoft Corporation
Author-email: ptvshelp@microsoft.com
License: MIT License
Location: /usr/local/lib/python2.7/dist-packages
Requires: azure-batch, azure-servicemanagement-legacy, azure-graphrbac, azure-storage, azure-mgmt, azure-servicebus

Running: Ubunut 16.04.3 LTS

Thanks in advance.

**Comment by vnimbalkar** [comment]
Resolved

**Comment by SHASHANKKS** [comment]
@vnimbalkar What was the solution /fix for the above problem. I am still facing the same issue with the latest azure_common python sdk package

**Comment by vnimbalkar** [comment]
For me there were some weird issues where I was unable to install azure-keyvault. 

Uninstalling manually downloaded packages and running below commands worked for me:

git clone git://github.com/Azure/azure-sdk-for-python.git
cd azure-sdk-for-python
python setup.py install

**Comment by SHASHANKKS** [comment]
Thanks!!
