### ISSUE TITLE
API documentation marks every field as required when it isn't

### ISSUE THREAD

**Issue by tonybaloney** [Azure/azure-sdk-for-python#18895]
The API documentation for the WebApp operations classes marks all arguments as `required`, when they are not.

For example, the `Site` envelope model shows https://docs.microsoft.com/en-us/python/api/azure-mgmt-web/azure.mgmt.web.v2020_09_01.models.site?view=azure-python everything as required.
In reality, you can send only `location` and `server_farm_id`.

This same bug in the documentation exists on all other models in this namespace

**Comment by tonybaloney** [comment]
Possibly fixed in the next release of the doc generator https://github.com/docascode/sphinx-docfx-yaml/pull/103

**Comment by tonybaloney** [comment]
@scbedd do you know when/if this patch to the docfx extension will take effect on the official docs site?

**Comment by swathipil** [comment]
@tonybaloney Thanks for your response! Directing this to the right people.

**Comment by scbedd** [comment]
@tonybaloney thanks for digging in here. That PR version **is** live. Unfortunately, while it fixes some cases, there are still some issues. AFAICT, I essentially fixed as far as I could with the current implementation of the generator. 

I'll add it to the to-do list to take another look to see if I missed anything, but I'm pretty certain we're out of luck until the generator is rewritten as a true `Builder` implementation. The required context to fix this **properly** everywhere is simply not present due to where the tool is monkeypatched into the sphinx pipeline.

@swathipil I think @danieljurek and I are probably good folks to take responsibility for this bug. Leaving it up to you or the triage folks 👍

**Comment by swathipil** [comment]
sounds good, thanks @scbedd! will reassign.

**Comment by scbedd** [comment]
Following up to confirm that this is fixed in the coming version of the docs.ms generator. (They took my advice on writing their own sphinx `builder`).

Unfortunately docs team is hitting some nasty release issues right now, and are all-hands on deck to get those resolved. Moving this to `tracking blocked`

**Comment by xiangyan99** [comment]
@scbedd I guess it is fixed?

**Comment by tonybaloney** [comment]
The referenced link is still showing everything as required and a quick browse around all operations have all parameters required when they aren't

**Comment by scbedd** [comment]
Unfortunately, the docs team is still rolling out the new generator.

**Comment by lmazuel** [comment]
Fix should be seen online now

**Comment by tonybaloney** [comment]
https://docs.microsoft.com/en-us/python/api/azure-mgmt-web/azure.mgmt.web.v2020_09_01.models.site?view=azure-python is still showing parameters like `hyper_v` as required, when they are not
