### ISSUE TITLE
azure.mgmt.datafactory.models.RunQueryFilter not working

### ISSUE THREAD

**Issue by ChronosSong** [Azure/azure-sdk-for-python#26558]
I query the specified pipeline within a week, add filters, no error is reported, but the returned result is all records in the time period
```
filter_parameters = RunFilterParameters(
        last_updated_after=last_sunday,
        last_updated_before=this_monday,
        filters=RunQueryFilter(operand="PipelineName", operator="Equals", values="D365")
    )
    credential = AzureCliCredential()
    datafactory_client = DataFactoryManagementClient(
        credential=credential,
        subscription_id=conf[azure_env]['subscription_id'],
        base_url=CLOUD.endpoints.resource_manager,
        credential_scopes=[CLOUD.endpoints.resource_manager + "/.default"]
    )
    query_data = datafactory_client.pipeline_runs.query_by_factory(
        resource_group_name=conf[azure_env]['resource_group_name'],
        factory_name=conf[azure_env]['factory_name'],
        filter_parameters=filter_parameters
    )
```
![image](https://user-images.githubusercontent.com/53171939/193185777-23dda2bd-4c11-4a7b-a042-170db2f3276a.png)

**Comment by mccoyp** [comment]
Hi @ChronosRoot, thank you for opening an issue! I'll tag some folks who can help and we'll get back to you as soon as possible.

**Comment by SaurabhSharma-MSFT** [comment]
@ChronosRoot Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Wzb123456789** [comment]
Hi @ChronosSong thanks for your feedback!

I found that there is some problem with the parameter format you fill in the function, I suggest you try the following ways to solve your problem，like
```python
query_data = datafactory_client.pipeline_runs.query_by_factory(
    resource_group_name=conf[azure_env]['resource_group_name'],
    factory_name=conf[azure_env]['factory_name'],
    filter_parameters={
        "last_updated_after": "last_sunday",
        "last_updated_before": "this_monday",
        "filters": [
            {
                "operand": "PipelineName",
                "operator": "Equals",
                "values": ["D365"]
            }
        ]
    }
)
```

**Comment by SaurabhSharma-MSFT** [comment]
@Wzb123456789 Thanks for looking into this but I have tried your code, but it is throwing error.
![image](https://user-images.githubusercontent.com/38112130/197841645-6aa5d53d-6cc3-4ddc-90cf-2164ae6d9f69.png)

**Comment by Wzb123456789** [comment]
@SaurabhSharma-MSFT 

The above solution is a little wrong, it has been corrected, please try again.

**Comment by ChronosSong** [comment]
I found that some parameters were lost during the serialization and conversion of json by filter_parameters.
Code `azure/mgmt/datafactory/operations/_pipeline_runs_operations.py` Line 283
`_json = self._serialize.body(filter_parameters, "RunFilterParameters")`
When i run the code.
filter_parameters `{'additional_properties': {}, 'continuation_token': None, 'last_updated_after': datetime.datetime(2022, 10, 17, 0, 0, tzinfo=zoneinfo.ZoneInfo(key='Asia/Shanghai')), 'last_updated_before': datetime.datetime(2022, 10, 24, 0, 0, tzinfo=zoneinfo.ZoneInfo(key='Asia/Shanghai')), 'filters': <azure.mgmt.datafactory.models._models_py3.RunQueryFilter object at 0x1031aec70>, 'order_by': None}`
But the returned json only has time left.
_json  `{'lastUpdatedAfter': '2022-10-16T16:00:00.000Z', 'lastUpdatedBefore': '2022-10-23T16:00:00.000Z'}`
I'm not very good at python serialization and am confused about it

**Comment by SaurabhSharma-MSFT** [comment]
Thanks @Wzb123456789 but I am still seeing error with the new code.
![image](https://user-images.githubusercontent.com/38112130/198365025-91a06a1a-31b9-4bc3-b112-ceca58da943a.png)

**Comment by msyyc** [comment]
Hi @ChronosSong The serialization error shall be caused by wrong input of `values`:
![image](https://user-images.githubusercontent.com/70930885/198511962-8788e785-a8b3-42ad-8f42-7122f4fffc78.png)
I fix it and please try https://github.com/Azure/azure-sdk-for-python/issues/26558#issuecomment-1288455249 again.

**Comment by SaurabhSharma-MSFT** [comment]
Thanks @msyyc.  It works for me now.

@ChronosSong  Waiting for your confirmation.

**Comment by ChronosSong** [comment]
@mccoyp Thanks for the guidance, it worked
