### ISSUE TITLE
AttributeError: module 'azure.core.pipeline.policies' has no attribute 'SensitiveHeaderCleanupPolicy'

### ISSUE THREAD

**Issue by ubaidmehmood93** [Azure/azure-sdk-for-python#34091]
from azure.core.credentials import AzureKeyCredential
from azure.ai.documentintelligence import DocumentIntelligenceClient
from azure.ai.documentintelligence.models import AnalyzeResult

endpoint = xxxxxxxxxxxxxxxx
key =xxxxxxxxxxxxxxxxxxx

document_intelligence_client = DocumentIntelligenceClient(endpoint=endpoint, credential=AzureKeyCredential(key))
with open(path_to_sample_documents, "rb") as f:
    poller = document_intelligence_client.begin_analyze_document(
        "prebuilt-layout", analyze_request=f, content_type="application/octet-stream"
    )

I was earlier using FormRecogniser and just wanted to shift to the Documentintelligence. But I am facing this error continuously. Please can we resolve it and any guidance. 
I have attached the image of the error as well.

The error is pasted below as well:
---> 11 document_intelligence_client = DocumentIntelligenceClient(endpoint=endpoint, credential=AzureKeyCredential(key))
     12 with open(path_to_sample_documents, "rb") as f:
     13     poller = document_intelligence_client.begin_analyze_document(
     14         "prebuilt-layout", analyze_request=f, content_type="application/octet-stream"
     15     )

File ~\Anaconda3\lib\site-packages\azure\ai\documentintelligence\_client.py:68, in DocumentIntelligenceClient.__init__(self, endpoint, credential, **kwargs)
     54 _policies = kwargs.pop("policies", None)
     55 if _policies is None:
     56     _policies = [
     57         policies.RequestIdPolicy(**kwargs),
     58         self._config.headers_policy,
     59         self._config.user_agent_policy,
     60         self._config.proxy_policy,
     61         policies.ContentDecodePolicy(**kwargs),
     62         self._config.redirect_policy,
     63         self._config.retry_policy,
     64         self._config.authentication_policy,
     65         self._config.custom_hook_policy,
     66         self._config.logging_policy,
     67         policies.DistributedTracingPolicy(**kwargs),
---> 68         policies.SensitiveHeaderCleanupPolicy(**kwargs) if self._config.redirect_policy else None,
     69         self._config.http_logging_policy,
     70     ]
     71 self._client: PipelineClient = PipelineClient(base_url=_endpoint, policies=_policies, **kwargs)
     73 self._serialize = Serializer()

AttributeError: module 'azure.core.pipeline.policies' has no attribute 'SensitiveHeaderCleanupPolicy'

<img width="575" alt="Error_Azure" src="https://github.com/Azure/azure-sdk-for-python/assets/100069780/d4e2ed44-8502-475d-8140-b251d422cbcb">

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you help to check the version of your azure-core library?

`SensitiveHeaderCleanupPolicy` was introduced in azure-core 1.28.0

**Comment by ubaidmehmood93** [comment]
> Thanks for reaching out.
> 
> Could you help to check the version of your azure-core library?
> 
> `SensitiveHeaderCleanupPolicy` was introduced in azure-core 1.28.0

It is 1.26.1, Do I need to update it?

**Comment by ubaidmehmood93** [comment]
> Thanks for reaching out.
> 
> Could you help to check the version of your azure-core library?
> 
> `SensitiveHeaderCleanupPolicy` was introduced in azure-core 1.28.0

Thank you its resolved by updating it :).

Also can you please guide me on this?

document_intelligence_client = DocumentIntelligenceClient(
    endpoint=endpoint, credential=AzureKeyCredential(key)
)


#folder_path = "C:/Users/MehmoodU/Downloads/Jupyter/proper flow/Oven_jobs/Tax_invoices/Test/"
folder_path = "C:/Users/MehmoodU/Downloads/Jupyter/proper flow/Oven_jobs/bill/"
all_files = os.listdir(folder_path)
pdf_files = [file for file in all_files if file.endswith('.pdf')]
pp = 0
for pdf_file in pdf_files:
    # Extract the file name without the extension
    pdf_name = os.path.splitext(pdf_file)[0]
    
    pp = 1 + pp
    print(pp)

    #with open("C:/Users/MehmoodU/Downloads/Jupyter/proper flow/Oven_jobs/Tax_invoices/Test/"+pdf_name+".pdf", "rb") as pdf_file:
    with open("C:/Users/MehmoodU/Downloads/Jupyter/proper flow/Oven_jobs/bill/"+pdf_name+".pdf", "rb") as pdf_file:
        print(pdf_file)
        time.sleep(1)
        poller = document_intelligence_client.begin_analyze_document("prebuilt-invoice", pdf_file)

    invoices = poller.result()
    print(invoices)
    
   <img width="421" alt="Error_Azure" src="https://github.com/Azure/azure-sdk-for-python/assets/100069780/ffa31d8a-f394-49f5-8166-832fe0674597">

**Comment by sdfzaheer** [comment]
Hi,

I have azure.core=1.28.0 but I am still seeing the same error SensitiveHeaderCleanupPolicy in azure ml studio .Can You please guide what could be other reasons?

Regards,
Sadaf Zaheer

**Comment by xiangyan99** [comment]
Let's make things simple. Please open new issues to track. :)

**Comment by xinyi-joffre** [comment]
I ran into this as well when testing new version of our extension for quantum! Is there a recommended way to handle this at the extension level, or does this require bug fix at azure-core level?

**Comment by juliapoloSC** [comment]
So what was the solution? I'm having this issue

**Comment by renata-gotler** [comment]
Hi, I have version azure-core 1.30.1 and I'm getting this error as well.

**Comment by noe-sautel** [comment]
Hello, azure-core @ 1.30.1, same error.

**Comment by masonhargrave** [comment]
Same error

**Comment by SeanFromIT** [comment]
Same error, introduced during az cli upgrade to 2.61.0. Downgrading back to 2.59.0 did not resolve.

**Comment by dnzau** [comment]
Running:  pip install --upgrade azure-core
Fixed the issue on my end
