### ISSUE TITLE
Gen AI monitoring is broken due to Marshmallow update

### ISSUE THREAD

**Issue by prise6** [Azure/azure-sdk-for-python#39075]
Hello,
Related to #39039 

When configuring monitoring, like this [example in documentation](https://learn.microsoft.com/en-us/azure/ai-studio/how-to/monitor-quality-safety?tabs=python#configure-monitoring).

Job failed with `cannot import name '_T' from 'marshmallow.fields' (/home/trusted-service-user/cluster-env/env/lib/python3.10/site-packages/marshmallow/fields.py)`

When digging in job log

```
# in logs/azureml/driver/librarymanager/*.log

# [...]
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip:
      - azure-cli-core~=2.45.0
      - azure-identity~=1.12.0
      - azure-ai-ml~=1.10.0
      - azure-keyvault-secrets==4.7.0
      - tiktoken==0.3.3
      - json5==0.9.11
      - scipy~=1.10.0
      - numpy~=1.21.0
      - pandas~=1.4.3
      - azureml-mlflow~=1.49.0
      - mltable~=1.3.0

# [...]

Collecting marshmallow<4.0.0,>=3.5 (from azure-ai-ml~=1.10.0->-r /usr/lib/library-manager/bin/condaenv.s2dyrgt_.requirements.txt (line 3))
  Downloading marshmallow-3.24.1-py3-none-any.whl.metadata (7.1 kB
```

Correct me if 'im wrong but i can't force the azure-ai-ml version in this component, so

* is there a workaround ?
* is it possible to update dependencies for this component ?

Thank you,

@kingernupur

**Comment by prise6** [comment]
Hello again,

Error still persists. Do you have planned actions about this error ?

![Image](https://github.com/user-attachments/assets/d883d712-a2f1-4b10-8a8d-dde2d01704d7)

Thank you,

**Comment by achauhan-scc** [comment]
issue is fixed 1.23.1

**Comment by prise6** [comment]
I understand that you fixed the marsmallow issue in the python sdk, but AzureML Monitoring is not fixed because the component version is not updated.

So i asked to your team in another repo: https://github.com/Azure/azureml-assets/issues/3775
