### ISSUE TITLE
No wait method for copy operation object when copying blob

### ISSUE THREAD

**Issue by LazzariPaolo** [Azure/azure-sdk-for-python#7043]
I am copying a blob from one subscription to the other with the _start_copy_from_url_ method.
I would like for my function to be blocking, and wait until the copy operation is completed.

I found mentioned in this example:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/azure/storage/blob/blob_client.py#L1283

that it should be possible to call the wait() function on the returned object.

> For all blob types, you can call status() on the returned polling object
        to check the status of the copy operation, or wait() to block until the
        operation is complete.

However, the following fails:

`copy = destination_blob.start_copy_from_url(source_blob)`
`copy.wait() `

**AttributeError: 'dict' object has no attribute 'wait'**

What am I missing?

**Comment by annatisch** [comment]
Thanks @LazzariPaolo ,
The documentation you see here is actually out of date - I will get it cleaned up asap.
The first iteration of the preview release had this blocking feature - but we removed it as a single copy operation can take days to complete.

You can create your own blocking function very simply, by using something like this that we use in our test suite. This function implements an arbitrary timeout, feel free to adapt as needed :)
```python
def wait_for_copy(self, blob):
    count = 0
    props = blob.get_blob_properties()
     while props.copy.status == 'pending':
        count = count + 1
        if count > 10:
            raise TimeoutError('Timed out waiting for async copy to complete.')
        time.sleep(5)
        props = blob.get_blob_properties()
    return props

destination_blob.start_copy_from_url(source_blob)
wait_for_copy(destination_blob)
```

**Comment by LazzariPaolo** [comment]
Hi @annatisch 

Great, thank you.
That works, however I am getting a weird message during the copy:

_Deserializer is not able to find None as valid enum in <enum 'LeaseDurationType'>_

Do you know what that means?

**Comment by annatisch** [comment]
Thanks @LazzariPaolo - you can ignore this - it is a bug that we have a fix for and is pending deployment. It is merely an empty warning - and not indicative of any actual error.

The fix has been merged here and is awaiting release:
https://github.com/Azure/msrest-for-python/pull/173

**Comment by LazzariPaolo** [comment]
Thanks for the clarification.

**Comment by talsheldon** [comment]
This issue wasn't resolved yet. I'm using Python 3.7 sdk version 12.5.0.

**Comment by varunsampat30** [comment]
The documentation now mentions "requires_sync" parameter for "start_copy_from_url". Does that mean that the wait function mentioned above is not required anymore?

**Comment by jakubwaller** [comment]
@annatisch The documentation is still out of date. Any progress on that?

**Comment by dzmitry-kankalovich** [comment]
This is super confusing that documentation is still out of date
