### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.profiles'

### ISSUE THREAD

**Issue by LazzariPaolo** [Azure/azure-sdk-for-python#8497]
```
$ pip freeze | grep 'azure-mgmt-storage'
azure-mgmt-storage==6.0.0
```

In Python 3.6.1:

```python
import azure.mgmt.storage
```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\paolol\AppData\Local\Programs\Python\Python36\lib\site-packages\azure\mgmt\storage\__init__.py", line 13, in <module>
>     from ._storage_management_client import StorageManagementClient
>   File "C:\Users\paolol\AppData\Local\Programs\Python\Python36\lib\site-packages\azure\mgmt\storage\_storage_management_client.py", line 15, in <module>
>     from azure.profiles import KnownProfiles, ProfileDefinition
> ModuleNotFoundError: No module named 'azure.profiles'

How can I fix this?

Indeed in *_storage_management_client.py* I see :

```python
from azure.profiles import KnownProfiles, ProfileDefinition
```

but *profiles* does not exist.

**Comment by LazzariPaolo** [comment]
I fixed this by uninstall the library and making sure pip was not using the cached dir when downloading:

```
$ pip uninstall azure-mgmt-storage
$ pip install azure-mgmt-storage --no-cache-dir
```

**Comment by stevenhurwitt** [comment]
i am seeing this same issue on a databricks cluster, but the above solution does not resolve the issue.

I am trying `import azure-mgmt-resource` and getting this error: 
`ModuleNotFoundError: No module named 'azure.profiles'`

Here is the output of my relevant pip freeze:
```
azure-common==1.1.8
azure-core==1.21.1
azure-eventhub==5.7.0
azure-graphrbac==0.61.1
azure-identity==1.7.0
azure-mgmt-authorization==0.61.0
azure-mgmt-containerregistry==8.2.0
azure-mgmt-core==1.3.0
azure-mgmt-keyvault==9.3.0
azure-mgmt-resource==21.0.0
azure-mgmt-storage==19.1.0
```

cluster python is Python 3.7.5

**Comment by paololazzari** [comment]
@stevenhurwitt I suggest you open a new issue - I don't think you'll get anyone looking at this one since it's closed
