### ISSUE TITLE
Service Bus: exception during complete()

### ISSUE THREAD

**Issue by Indy2222** [Azure/azure-sdk-for-python#9144]
We are getting the following exception when calling `complete()`
on a message received from Service Bus. Note that this happens on
messages which are being "processed" for a long time and
periodically (very 10 seconds) renewed before competition.

```
Unhandled exception: Failed to accept message. Error: Unable to send message dispostition 'accepted' for message number 1
Traceback (most recent call last):
  File ".../lib/python3.7/site-packages/azure/servicebus/aio/async_message.py", line 75, in complete
    await self._loop.run_in_executor(None, self.message.accept)
  File ".../lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File ".../lib/python3.7/site-packages/uamqp/message.py", line 375, in accept
    self._settler(self._response)
  File ".../lib/python3.7/site-packages/uamqp/receiver.py", line 203, in _settle_message
    self._receiver.settle_accepted_message(message_number)
  File "./src/message_receiver.pyx", line 70, in uamqp.c_uamqp.cMessageReceiver.settle_accepted_message
  File "./src/message_receiver.pyx", line 74, in uamqp.c_uamqp.cMessageReceiver.settle_accepted_message
RuntimeError: Unable to send message dispostition 'accepted' for message number 1
```

This happens with uamqp version `1.2.4` and `azure-servicebus` version `0.50.1`.

**Comment by yunhaoling** [comment]
Hello @Indy2222 , thanks for reporting.

Does the issue happen when you're using service bus with uamqp 1.1.0 or uamqp 1.2.3?

**Comment by Indy2222** [comment]
As I have initially reported, this is hapenning with uamqp 1.2.3.

**Comment by yunhaoling** [comment]
Hello @Indy2222 , thanks for the information.

Can you try running your program with uamqp v1.1.0 by `pip install uamqp==1.1.0` to see if the issue mitigate?

We've done several bug fix and improvement in the uamqp library 1.2.*, so wondering whether these changes breaks the ServiceBus.

**Comment by engebret** [comment]
Hi @yunhaoling , has there been any further work on this issue?  We may have just hit the same problem in our environment.  Service-bus 0.50.2 and uamqp 1.2.7.

Thanks --

**Comment by yunhaoling** [comment]
Hi @Indy2222  and @engebret ,

from the error log that @Indy2222 has posted, this error usually occurs when the receiver that message related to is closed.

The service side would choose to disconnect a receiver if there's no activity in 10 mins. It might be the reason you're encountering this error (or you close that receiver proactively).
 
Would you be able to share me with the problematic code?

-------------------

On the other hand:

We have made a patch version which enhanced the renew lock operation to keep the receiver link alive.

It would be great if you could take a try to see if this solves your problem. You could either choose to renew lock periodically by yourself or use our `azure.servicebus.AutoLockRenew` class:

```python
with receiver:
    auto_lock_renew = AutoLockRenew()
    msgs = receiver.fetch_next(max_batch_size=size, timeout=time)
    with auto_lock_renew:
        for msg in msgs:
            auto_lock_renew.register(msg, timeout=lock_duration)  # auto_lock_renew will handle the lock renew ops for you for *lock_duration* time.

        for msg in msgs:
            # long period processing
            msg.complete()
```

[azure_servicebus-0.50.3b1.zip](https://github.com/Azure/azure-sdk-for-python/files/4602051/azure_servicebus-0.50.3b1.zip) (@engebret this is the same patch I provided you in another github issue thread.)

Looking forward to your reply.

**Comment by yunhaoling** [comment]
@Indy2222 @engebret , is there any update from your side?

**Comment by engebret** [comment]
Hi @yunhaoling - we have been running on that 0.50.3b1 update you previously provided & it has been working for our cases in test.  When I last commented on this issue we observed a similar failure mode, but I now suspect one system had not been updated with this patch properly.  I will let you know if we see anything fail, and look forward to getting the official fix release.

**Comment by yunhaoling** [comment]
hey @Indy2222 @engebret , we've released azure-servicebus v0.50.3 today which brings the fix for keeping receiver link alive when renewing locks. I hope this would have the issue resolved. Please update your library dependency.

---

The important thing worth your attention here is that v0.50.3 would be our final release for v0.50 -- it is about to be deprecated.

We're shipping a brand-new [azure-servicebus v7.0.0](https://pypi.org/project/azure-servicebus/7.0.0b2/) (which is currently in b2) to build a more user friendly and productive library following our SDK design guidelines. We decided not to maintain the old preview (v0.50) library which will never go GA.

We've provided [migration guide on v0.50 to v7](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/servicebus/azure-servicebus/migration_guide.md) to help get you onboard.

Apologize for the inconvenience we bring to you and thanks for your understanding.

We're looking forward to you trying our latest preview library and feedback is most welcome.

**Comment by stupidtools** [comment]
I'm still getting this issue.  The error only occurs on some of the messages when I try to complete them, and will happen even if I call the complete method immediately after the fetch_next method is finished.  
`azure.servicebus.common.errors.MessageSettleFailed: Failed to complete message. Error: Unable to send message dispostition 'accepted' for message number 1`

  As of right now, v7 looks to still be in beta.  How would you suggest I proceed?
